"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Import } from "lucide-react"
import { toast } from "@/components/ui/use-toast"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"

interface ImportDialogProps {
  onImport: (importText: string) => void
}

export function ImportDialog({ onImport }: ImportDialogProps) {
  const [isOpen, setIsOpen] = useState(false)
  const [importText, setImportText] = useState("")

  const handleImport = () => {
    if (importText.trim() === '') {
      toast({
        title: "Empty input",
        description: "Please paste some CSS code to import.",
        variant: "destructive",
      })
      return
    }
    onImport(importText)
    setIsOpen(false)
    setImportText("")
  }

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" onClick={() => setIsOpen(true)}>
          <Import className="h-4 w-4 mr-2" /> Import Gradient
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[525px]">
        <DialogHeader>
          <DialogTitle>Import Gradient</DialogTitle>
          <DialogDescription>Paste CSS code containing a mesh gradient previously generated by this tool.</DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="text-sm text-muted-foreground mb-2">
            <p>You can paste:</p>
            <ul className="list-disc pl-4 mt-1 space-y-1">
              <li>Complete CSS with <code className="bg-secondary text-secondary-foreground px-1 py-0.5 rounded">background:</code> property</li>
              <li>Just the gradient part (multiple <code className="bg-secondary text-secondary-foreground px-1 py-0.5 rounded">radial-gradient()</code> definitions)</li>
              <li>CSS with newlines and formatting is supported</li>
            </ul>
            <p className="mt-2">Each gradient must include:</p>
            <ul className="list-disc pl-4 mt-1 space-y-1">
              <li>Position: <code className="bg-secondary text-secondary-foreground px-1 py-0.5 rounded">at X% Y%</code></li>
              <li>Color: <code className="bg-secondary text-secondary-foreground px-1 py-0.5 rounded">COLOR 0%</code></li>
              <li>Transparency: <code className="bg-secondary text-secondary-foreground px-1 py-0.5 rounded">transparent Z%</code></li>
            </ul>
          </div>
          <Textarea
            placeholder="background: radial-gradient(at 0% 0%, #ff5e62 0%, transparent 50%), radial-gradient(at 100% 0%, #ff9966 0%, transparent 50%)..."
            value={importText}
            onChange={(e) => setImportText(e.target.value)}
            className="min-h-[150px]"
          />
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => setIsOpen(false)}>
            Cancel
          </Button>
          <Button onClick={handleImport}>
            Import
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
} 